import { murmurhash3 } from './hash';
import type { FingerprintData } from './types';

export function getCanvasFingerprint(): FingerprintData[] {
  try {
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d')!;
    ctx.textBaseline = 'top';
    ctx.font = '14px Arial';
    ctx.fillStyle = '#f60';
    ctx.fillRect(125, 1, 62, 20);
    ctx.fillStyle = '#069';
    ctx.fillText('BrowserInfo • Fingerprint', 2, 15);
    ctx.fillStyle = 'rgba(102, 204, 0, 0.7)';
    ctx.fillText('BrowserInfo • Fingerprint', 4, 17);

    const dataUrl = canvas.toDataURL();
    const hash = murmurhash3(dataUrl);

    return [
      {
        category: 'Canvas',
        key: 'Fingerprint',
        value: hash,
        tooltip: 'Unique fingerprint derived from rendered canvas. Generated by hashing a canvas drawing output.'
      },
      {
        category: 'Canvas',
        key: 'Data (truncated)',
        value: dataUrl.slice(0, 80) + '...',
        tooltip: 'Raw canvas data (truncated). Shows how canvas output looks before hashing.'
      },
    ];
  } catch {
    return [{
      category: 'Canvas',
      key: 'Status',
      value: 'Blocked',
      tooltip: 'Canvas fingerprinting blocked or not supported.'
    }];
  }
}
